/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/App/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/App/dashboard/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/App',
  path: '/App',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/App': typeof AppRouteRouteWithChildren
  '/App/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/App': typeof AppRouteRouteWithChildren
  '/App/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/App': typeof AppRouteRouteWithChildren
  '/App/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/App' | '/App/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/App' | '/App/dashboard'
  id: '__root__' | '/' | '/App' | '/App/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/App/dashboard/': {
      id: '/App/dashboard/'
      path: '/dashboard'
      fullPath: '/App/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
